services:
    web:
        build: .
        container_name: webserver
        volumes:
            - "./src:/var/www/html/"
        networks:
            - web_network
        restart: unless-stopped

    nginx-proxy:
        image: owasp/modsecurity-crs:4.24.0-nginx-202603010803
        container_name: nginx-proxy
        user: root
        environment:
            - BACKEND=http://web:80
            - MODSEC_AUDIT_LOG=/var/log/nginx/modsec_audit.log
        ports:
            - "80:80"
        volumes:
            - ./config/nginx-proxy/conf.d:/etc/nginx/templates/conf.d:ro
            - ./logs/nginx-proxy:/var/log/nginx
        networks:
            - web_network
        restart: unless-stopped

networks:
    web_network:
        driver: bridge
