# Oculta información del servidor
server_tokens off;

server {
    # Escucha en HTTP (puerto 80) dentro del contenedor/host donde corre Nginx
    listen 80;
    # “_” como catch-all: este vhost responde a cualquier Host si no hay otro server_name más específico
    server_name _;

    # Logs: claves para depurar el proxy y para enviar al SIEM
    access_log /var/log/nginx/access.log;
    # Nivel warn = warnings + errors + crit...
    error_log /var/log/nginx/error.log warn;

    # --- CABECERAS DE SEGURIDAD ---
    # CSP: Solo carga activos del propio dominio
    add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; object-src 'none';" always;

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;

    location / {
        # Redirige todo el tráfico al servidor web
        proxy_pass http://web:80;      

        # Cabeceras típicas para que la app “sepa” que está detrás de un proxy y pueda loguear bien:
        # Host: qué hostname pidió el cliente
        proxy_set_header Host              $host;
        # X-Real-IP: IP real del cliente (la ve la app)
        proxy_set_header X-Real-IP         $remote_addr;
        # X-Forwarded-For: cadena de IPs por las que ha pasado (cliente + proxies)
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        # X-Forwarded-Proto: http/https según el esquema de entrada al proxy
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}